### ISSUE TITLE
add the new 'minimal-ui' tag

### ISSUE THREAD

**Issue by obiot** [melonjs/boilerplate#11]
this is new in iOS 7.1 and allows to hide the URL bar, I have not yet tested it to really see how it behaves, but I believe that would nice to add in our boilerplate :)

**Comment by parasyte** [comment]
`minimal-ui` was removed in iOS8: https://developer.apple.com/library/ios/releasenotes/General/RN-iOSSDK-8.0/

**Comment by obiot** [comment]
really.... ? so it's really like at every single iOS update they are screwing up with something related to HTML5 :(

**Comment by 1e4** [comment]
@obiot It's apple, expect nothing different *sighs*
