### ISSUE TITLE
Grunt Cli not set as a dependency.

### ISSUE THREAD

**Issue by JohnRodney** [melonjs/boilerplate#18]
Thanks for the library I just noticed that grunt-cli wasn't set as a dependency so when its first downloaded if the user doesn't either `npm install -g grunt-cli` or `npm install --save-dev grunt-cli` then they won't be able to progress through the rest of the readme.

We could either add that to the readme docs or adjust the package.json to have a devdependency on grunt-cli.

**Comment by JohnRodney** [comment]
https://github.com/melonjs/boilerplate/pull/19

**Comment by parasyte** [comment]
Hi @JohnRodney The problem with requiring grunt-cli as a dependency is that the CLI executable won't be in the user's path, so this doesn't actually solve the problem. See also [this commit discussion](https://github.com/melonjs/melonJS/commit/8f9c0179d2f267f998aa42eeedca7fc6d3585f58#commitcomment-11512973) on the library repo where I raised the same concerns.

**Comment by JohnRodney** [comment]
@parasyte understood can we add the `npm install -g grunt-cli` to the docs?

**Comment by parasyte** [comment]
Yes absolutely! That is missing for sure. I don't have access to my laptop at the moment, but I'll get to it soon. In the meantime, you can open another PR for that if you like.
