### ISSUE TITLE
npm install chromium-pickle

### ISSUE THREAD

**Issue by Tiagojdferreira** [melonjs/boilerplate#20]
I have just cloned the repo, and as I try to do npm install I have the following error due to the chromium-pickle package:

```
CXX(target) Release/obj.target/native_mate/node_modules/native-mate/vendor/src/native_mate/arguments.o
c++: error: unrecognized command line option '-stdlib=libstdc++'
```

From what I could found online, it seems to be a problem related to OS X Yosemite. Any help would be appreciated.

**Comment by parasyte** [comment]
I haven't seen that one before... A dumb workaround is to remove `grunt-asar`from package.json. It's only used for building the electron bundle.

**Comment by obiot** [comment]
weird, as I also run yosemite, and never got this issue on my side too....

**Comment by luizfilipe** [comment]
I've got this issue on macbook pro mid 2012, nodejs 5.0.0 and 4.2.1 also.

**Comment by gintsgints** [comment]
This should depend on node you are using. Newer node has different node-gyp imho.

**Comment by luizfilipe** [comment]
Ok then, but it has any other to build game to desktop platforms?

**Comment by parasyte** [comment]
Looks like this will be fixed by a newer version of `asar`: https://github.com/atom/asar/pull/28 We just need to update dependencies.

**Comment by parasyte** [comment]
@luizfilipe @Tiagojdferreira Please try the new development branch `update-asar`. You might want to remove your `node_modules` directory and run `npm install` again. This worked for me.

**Comment by Cross22** [comment]
Similar problem seen on Windows 10. Update-asar branch fixed it.

**Comment by obiot** [comment]
i just re-installed the whole thing from scratch on a freshly repackaged machine (OSX El Capitan) and did not encounter a single issue, and I used the latest version possible for everything (nodejs, etc...)

**Comment by parasyte** [comment]
@Cross22 Thanks for confirmation. I'm going to merge it into master.
