### ISSUE TITLE
Add grunt task that builds application manifest file.

### ISSUE THREAD

**Issue by agmcleod** [melonjs/boilerplate#21]
The application.manifest is a file that helps desktop & mobile browsers cache data for offline use. We can generate a manifest that contains the urls to the assets, compiled JS and any html. Store the a timestamp for when it was generated. That way when the person runs the grunt task again, the file will always get changed. It's the only way the browser knows to re-fresh the cache.

**Comment by parasyte** [comment]
Yeah!
