### ISSUE TITLE
grunt-asar returns error

### ISSUE THREAD

**Issue by arnaldorusso** [melonjs/boilerplate#25]
After trying to `npm install `
follows the code:

npm ERR! git clone git@github.com:github:bwin/grunt-asar Cloning into bare repository '/home/yepan/.npm/_git-remotes/git-github-com-github-bwin-grunt-asar-992302ac'...
npm ERR! git clone git@github.com:github:bwin/grunt-asar fatal: remote error: 
npm ERR! git clone git@github.com:github:bwin/grunt-asar    is not a valid repository name
npm ERR! git clone git@github.com:github:bwin/grunt-asar   Email support@github.com for help
npm ERR! notarget No compatible version found: grunt-asar@'github:bwin/grunt-asar#update-asar'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.9.0-2-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/yepan/Downloads/boilerplate
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/yepan/Downloads/boilerplate/npm-debug.log
npm ERR! not ok code 0

**Comment by parasyte** [comment]
What version of `node` and `npm` are you using? It is working for me here.

```
parasyte@Turkatron:~/Desktop/boilerplate (master)$ node --version
v7.5.0
parasyte@Turkatron:~/Desktop/boilerplate (master)$ npm --version
4.1.2
```

**Comment by parasyte** [comment]
Nope, it's not the node version. I just tried it with node 4.8.2, and it's still working.

**Comment by arnaldorusso** [comment]
Thanks @parasyte I have deleted the `node_modules` and now it's ok!
