### ISSUE TITLE
Remove need to install grunt-cli globally

### ISSUE THREAD

**Issue by ssangervasi** [melonjs/boilerplate#30]
We can streamline getting started with this boilerplate by making a small addition to `package.json` that removes the need to install grunt-cli  globally:

```json
"scripts": {
  "serve": "grunt serve"
},
```

Then we can get up and running using `npm run serve` without any additional steps, which I think makes the readme even more pleasant.

**Comment by obiot** [comment]
very good suggestion and done ! thanks :)

**Comment by obiot** [comment]
this will also help transparently moving away from grunt (still looking at moving to rollup like we did for melonjs itself)
