### ISSUE TITLE
Loading "asar.js" tasks...ERROR >> ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by evan-boissonnot** [melonjs/boilerplate#34]
Hi, when I launch grunt serve on the directory, in my own pc, i got this error : 
Loading "asar.js" tasks...ERROR
>> ReferenceError: primordials is not defined

About the context : 

Node version : v12.16.1

Package json : same as yours

grunt-cli v1.3.2
grunt v1.1.0

OS: windows 10 pro

**Comment by obiot** [comment]
fixed !

**Comment by manomoul** [comment]
I also have this issue.

**Comment by YearOfTheFinch** [comment]
Same issue.

Windows 10
Node 12.16.1
Globally-installed grunt-cli@1.3.2
Locally-installed grunt@1.2.1

**Comment by kalyanchakravarthys** [comment]
is this issue fixed?
if yes, how to fix it?

**Comment by kalyanchakravarthys** [comment]
This solution worked for me
- Uninstall Node Modules
- Create a file "npm-shrinkwrap.json" in the same directory where you have placed package.json and copy the below code to the this file
 `{
    "dependencies": {
        "graceful-fs": {
            "version": "4.2.2"
        }
    }
}`
- npm install
- npm run build
- npm run serve

**Comment by tvortsa** [comment]
have same error, well this project have lot of "deprecation" npm warnings (
