### ISSUE TITLE
how to fix problem the primodials is not defined

### ISSUE THREAD

**Issue by high4123** [melonjs/boilerplate#35]
I tried to run distribution. But failed

I tried command "$grunt dist" but received the failed response

Here response

Loading "asar.js" tasks...ERROR
>> ReferenceError: primordials is not defined
Warning: Task "asar" not found. Use --force to continue.

Aborted due to warnings.

https://user-images.githubusercontent.com/16911517/86319158-cb369d80-bc6e-11ea-83c9-767245a4ba3a.png

How to fix problem the primodials is not defined

My system is

node -v : v12.16.1
npm -v : 6.14.5
grunt-cli : 1.3.2
OS : macOS Catalina 10.15.5

Please help me... Have a nice day~ ^^;

**Comment by obiot** [comment]
after updating my environment following [this commit](https://github.com/melonjs/boilerplate/commit/dd1f3fb8936b6edb03d6970540139d143b315fca), I'm not able to replicate this issue actually (I'm also on macOS Catalina).

could you also update your boilerplate and run a `npm update` to make sure that all dependencies are up to date ? (`grunt-asar` was updated to version 0.8.3 on my side during the process) 

to be noted that following this commit the below commands changes:
* `grunt` -> `npm run build`
* `grunt serve` -> `npm run serve`
* `grunt dist` -> `npm run dist`

let me know if this fixes your issue,

thanks.

**Comment by p-w-g** [comment]
I had similar issue on win10.

I've uninstalled node 12, then downloaded installer for node 10, so currently with node 10.21.0 Ive managed to run `grunt dist`.
`npm run dist` works now as well.

**Comment by high4123** [comment]
The problem is solved. Thank you!

**Comment by melvinkcx** [comment]
@high4123 Do you mind sharing how you solve the problem?
