### ISSUE TITLE
this garbage crash on npm install

### ISSUE THREAD

**Issue by SpyrariSpagetify** [melonjs/boilerplate#38]
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: boilerplate@2.3.0
npm ERR! Found: grunt@1.4.1
npm ERR! node_modules/grunt
npm ERR!   dev grunt@"^1.4.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer grunt@"~0.4.0" from grunt-asar@0.8.3
npm ERR! node_modules/grunt-asar
npm ERR!   dev grunt-asar@"github:bwin/grunt-asar#update-asar" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Sanic\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sanic\AppData\Local\npm-cache\_logs\2022-03-28T16_49_10_234Z-debug-0.log

**Comment by obiot** [comment]
yeah, as indicated in the README, this boilerplate is deprecated (for more than one year now)since the release of melonJS version 9.0, so totally expected for this one not work, as not maintained anymore
